server.port=8080

//Langchain4j
langchain4j.open-ai.chat-model.api-key=demo

//Spring JPA
spring.datasource.url=jdbc:postgresql://dpg-d6lh69ntskes739ouel0-a:5432/platzi_play_db_s6l9
spring.datasource.username=victor
spring.datasource.password=fs13YYFPFMPU4bJpNsIbgXgYSIYDCuJ7
//spring.sql.init.mode=always

//spring.jpa.hibernate.ddl-auto=update